seed: 9

federation:
  num_rounds: 50
  local_epochs: 5
  batch_size: 32

training:
  lr: 0.001
  optimizer: 'adam'

model:
  name: 'xpatch'    #'xpatch', 'rnn', 'lstm', 'gru', 'mlp', 'dlinear', 'pyraformer',
                      #'fedformer', 'timesnet', 'patchtst'
  pfl_enabled: true

results:
  save_dir_prefix: 'result/'

privacy:
  enabled: true
  clipping_norm: 1.5
  noise_sigma:
    seasonal: 0.001
    trend: 0.005

aggregation:
  name: 'fedavg'  # 'fedavg', 'fedprox', 'fedyogi', 'fedavgm', 'fedadam', 'fedadagrad', 'fedmedian'
  mu: 0.01

clustering:
  enabled: true
  warmup_rounds: 9

  method: 'spectral'  # 可选: 'kmeans', 'gmm', 'spectral', 'leiden', 'finch'

  num_clusters: 4
  eps: 0.5
  min_samples: 2
  recluster_every_n_rounds: 100

  affinity: 'nearest_neighbors'
  n_neighbors: 5

  linkage: 'ward'



# 数据与设备设置
#data:
#  mode: 'multi_file'  # 使用多文件模式
#  files:
#    - 'data/batch-1.xlsx'
#    - 'data/batch-2.xlsx'
#    - 'data/batch-3.xlsx'
##    - 'data/batch-4.xlsx'
##    - 'data/batch-5.xlsx'
#  window_size: 50
#  pre_len: 200
#  max_capacity: 2.0
#  enc_in: 6
#  device: 'cuda'

#data:
# mode: 'single_file_multi_client'
# single_file: 'data/batch-1.xlsx'
# window_size: 50
# pre_len: 200
# max_capacity: 2.0
# enc_in: 6
# device: 'cuda'

data:
  mode: 'multi_file_all_sheets'
  files:
#    - 'data/batch-1.xlsx'
#    - 'data/batch-2.xlsx'
#    - 'data/batch-3.xlsx'
    - 'data/batch-4.xlsx'
    - 'data/batch-5.xlsx'
  window_size: 100
  pre_len: 500
  max_capacity: 1.1
  enc_in: 6
  device: 'cuda'

